### ISSUE TITLE
placeholderLabel and the noEntriesFoundLabel as an input property

### ISSUE THREAD

**Issue by malagradecido** [bithost-gmbh/ngx-mat-select-search-example#1]
thanks for everything. it would be very helpful to place the placeholderLabel and the noEntriesFoundLabel as an input property

**Comment by macjohnny** [comment]
@malagradecido thanks for your issue.
I added the inputs to the https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/README.md#api
If you have any further suggestions, please open another issue, preferrably in the https://github.com/bithost-gmbh/ngx-mat-select-search/issues repository. If you could come up with a corresponding pull request, this would be great.
