### ISSUE TITLE
Show result first for server side search

### ISSUE THREAD

**Issue by xenocent** [bithost-gmbh/ngx-mat-select-search-example#3]
how to show all result when the filter text is empty?

**Comment by macjohnny** [comment]
in the example, the search input is filtered here:

https://github.com/bithost-gmbh/ngx-mat-select-search-example/blob/42c3208c2fc1e2f1c97d55276e36e3f228b83c2e/src/app/examples/05-server-side-search-example/server-side-search-example.component.ts#L39

**Comment by macjohnny** [comment]
@xenocent please provide more details / example code
